# Generated by Django 5.0.7 on 2024-08-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
