# Generated by Django 5.0.7 on 2024-08-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
