# Generated by Django 5.0.7 on 2024-08-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0005_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
