# Generated by Django 5.0.7 on 2024-08-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0010_polloption_likes_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polloption',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
