# Generated by Django 5.0.7 on 2024-09-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0011_remove_polloption_likes_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
