# Generated by Django 5.0.7 on 2024-09-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0017_vote_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='image',
        ),
    ]
