# Generated by Django 5.0.7 on 2024-09-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0018_remove_poll_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_image',
            field=models.ImageField(blank=True, null=True, upload_to='poll_images/'),
        ),
    ]
