# Generated by Django 5.0.7 on 2024-09-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0019_poll_poll_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='poll_image',
            new_name='image',
        ),
    ]
